server:
  port: 8083
  error:
    include-message=always:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:location-query-svc-keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: location-query-svc-key
    enabled: true
management:
  health:
    binders:
      enabled: true
  endpoint:
    include: health,info,metrics,prometheus
app:
  security:
    clientId: spring-test-app
spring:
  application:
    name: location-query
  r2dbc:
    pool:
      enabled: true
      initial-size: 50
      max-size: 100
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://location-keycloak.azurewebsites.net/realms/keycloak-demo/protocol/openid-connect/certs"
logging:
  level:
    org.springframework.security: DEBUG
